// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ChannelAdam.Wcf.BehaviourSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ConsumingServicesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ConsumingServices.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Consuming Services", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Consuming Services")))
            {
                ChannelAdam.Wcf.BehaviourSpecs.ConsumingServicesFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 001 - Positive - Should use a factory method to create a new " +
            "service channel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_001_Positive_ShouldUseAFactoryMethodToCreateANewServiceChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 001 - Positive - Should use a factory method to create a new " +
                    "service channel", new string[] {
                        "UnitTest"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("a factory method to create a new service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
testRunner.When("the service consumer is created with the factory method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
testRunner.Then("the service consumer used the factory method to create a new service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 002 - Positive - Should automatically create a new service ch" +
            "annel as needed when the previous one has been closed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_002_Positive_ShouldAutomaticallyCreateANewServiceChannelAsNeededWhenThePreviousOneHasBeenClosed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 002 - Positive - Should automatically create a new service ch" +
                    "annel as needed when the previous one has been closed", new string[] {
                        "UnitTest"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
testRunner.Given("a factory method to create a new service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
testRunner.When("the service consumer is created with the factory method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
testRunner.And("the service channel is closed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
testRunner.And("the service channel is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
testRunner.Then("the service consumer used the factory method to create a new service channel agai" +
                    "n", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 005 - Positive - Should be created successfully from Unity Io" +
            "C")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_005_Positive_ShouldBeCreatedSuccessfullyFromUnityIoC()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 005 - Positive - Should be created successfully from Unity Io" +
                    "C", new string[] {
                        "UnitTest"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
testRunner.Given("a configured Unity IoC container", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
testRunner.When("the service consumer is created with the Unity IoC container", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
testRunner.Then("the service consumer was created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 006 - Positive - Should be created successfully from AutoFac " +
            "IoC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_006_Positive_ShouldBeCreatedSuccessfullyFromAutoFacIoC()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 006 - Positive - Should be created successfully from AutoFac " +
                    "IoC", new string[] {
                        "UnitTest"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
testRunner.Given("a configured Autofac IoC container", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
testRunner.When("the service consumer is created with the Autofac IoC container", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
testRunner.Then("the service consumer was created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 007 - Positive - Should be created successfully from Simple I" +
            "njector IoC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_007_Positive_ShouldBeCreatedSuccessfullyFromSimpleInjectorIoC()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 007 - Positive - Should be created successfully from Simple I" +
                    "njector IoC", new string[] {
                        "UnitTest"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
testRunner.Given("a configured Simple Injector IoC container", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
testRunner.When("the service consumer is created with the Simple Injector IoC container", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
testRunner.Then("the service consumer was created successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 010 - Positive - Should successfully synchronously invoke a s" +
            "ervice operation on a service channel proxy")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_010_Positive_ShouldSuccessfullySynchronouslyInvokeAServiceOperationOnAServiceChannelProxy()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 010 - Positive - Should successfully synchronously invoke a s" +
                    "ervice operation on a service channel proxy", new string[] {
                        "UnitTest"});
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
testRunner.Given("a factory method to create a new service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 46
testRunner.When("the service consumer is created with the factory method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
testRunner.And("an operation is invoked synchronously", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
testRunner.Then("the operation was invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 011 - Positive - Should successfully asynchronously invoke a " +
            "service operation on a service channel proxy")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_011_Positive_ShouldSuccessfullyAsynchronouslyInvokeAServiceOperationOnAServiceChannelProxy()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 011 - Positive - Should successfully asynchronously invoke a " +
                    "service operation on a service channel proxy", new string[] {
                        "UnitTest"});
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
testRunner.Given("a factory method to create a new service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
testRunner.When("the service consumer is created with the factory method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
testRunner.And("an operation is invoked asynchronously", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
testRunner.Then("the operation was invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 015 - Positive - Should by default keep the service channel o" +
            "pen and reusable when a FaultException occurs while invoking a service operation" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_015_Positive_ShouldByDefaultKeepTheServiceChannelOpenAndReusableWhenAFaultExceptionOccursWhileInvokingAServiceOperation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 015 - Positive - Should by default keep the service channel o" +
                    "pen and reusable when a FaultException occurs while invoking a service operation" +
                    "", new string[] {
                        "UnitTest"});
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
testRunner.Given("a service consumer is created with an operation that throws a \'fault\' exception", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
testRunner.When("the operation is called via the Consume method and a \'fault\' exception occurs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
testRunner.Then("the service channel was not closed or aborted, and remains open and usable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 016 - Positive - Should use the default retry policy specifie" +
            "d on the service consumer to perform retries with the Call method")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_016_Positive_ShouldUseTheDefaultRetryPolicySpecifiedOnTheServiceConsumerToPerformRetriesWithTheCallMethod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 016 - Positive - Should use the default retry policy specifie" +
                    "d on the service consumer to perform retries with the Call method", new string[] {
                        "UnitTest"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 67
testRunner.Given("a service consumer is created with an operation that throws a \'communication\' exc" +
                    "eption", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
testRunner.And("the service consumer has a default retry policy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
testRunner.When("the operation is called via the Consume method and a \'communication\' exception oc" +
                    "curs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
testRunner.Then("the operation was invoked multiple times due to the retry policy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 71
testRunner.Then("the exception behaviour was invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 017 - Positive - Should use the default retry policy specifie" +
            "d on the service consumer to perform retries with the Operations property")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_017_Positive_ShouldUseTheDefaultRetryPolicySpecifiedOnTheServiceConsumerToPerformRetriesWithTheOperationsProperty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 017 - Positive - Should use the default retry policy specifie" +
                    "d on the service consumer to perform retries with the Operations property", new string[] {
                        "UnitTest"});
#line 74
this.ScenarioSetup(scenarioInfo);
#line 75
testRunner.Given("a service consumer is created with an operation that throws a \'communication\' exc" +
                    "eption", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
testRunner.And("the service consumer has a default retry policy with a retry policy attempt excep" +
                    "tion behaviour", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
testRunner.When("the operation is called via the Operations property and a \'communication\' excepti" +
                    "on occurs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
testRunner.Then("the operation was invoked multiple times due to the retry policy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 79
testRunner.Then("the exception behaviour was invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 020 - Negative - Should by default close the service channel " +
            "when a CommunicationException occurs while invoking a service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_020_Negative_ShouldByDefaultCloseTheServiceChannelWhenACommunicationExceptionOccursWhileInvokingAServiceOperation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 020 - Negative - Should by default close the service channel " +
                    "when a CommunicationException occurs while invoking a service operation", new string[] {
                        "UnitTest"});
#line 85
this.ScenarioSetup(scenarioInfo);
#line 86
testRunner.Given("a service consumer is created with an operation that throws a \'communication\' exc" +
                    "eption", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 87
testRunner.When("the operation is called via the Consume method and a \'communication\' exception oc" +
                    "curs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
testRunner.Then("the service channel was closed and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 021 - Negative - Should by default close the service channel " +
            "when a TimeoutException occurs while invoking a service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_021_Negative_ShouldByDefaultCloseTheServiceChannelWhenATimeoutExceptionOccursWhileInvokingAServiceOperation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 021 - Negative - Should by default close the service channel " +
                    "when a TimeoutException occurs while invoking a service operation", new string[] {
                        "UnitTest"});
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
testRunner.Given("a service consumer is created with an operation that throws a \'timeout\' exception" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 93
testRunner.When("the operation is called via the Consume method and a \'timeout\' exception occurs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
testRunner.Then("the service channel was closed and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 022 - Negative - Should by default close the service channel " +
            "when an unexpected Exception occurs while invoking a service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_022_Negative_ShouldByDefaultCloseTheServiceChannelWhenAnUnexpectedExceptionOccursWhileInvokingAServiceOperation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 022 - Negative - Should by default close the service channel " +
                    "when an unexpected Exception occurs while invoking a service operation", new string[] {
                        "UnitTest"});
#line 97
this.ScenarioSetup(scenarioInfo);
#line 98
testRunner.Given("a service consumer is created with an operation that throws a \'unexpected\' except" +
                    "ion", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 99
testRunner.When("the operation is called via the Consume method and a \'unexpected\' exception occur" +
                    "s", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 100
testRunner.Then("the service channel was closed and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 023 - Negative - Should by default close the service channel " +
            "when a ThreadAbortedException occurs while invoking a service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        public virtual void ConsumingServices_023_Negative_ShouldByDefaultCloseTheServiceChannelWhenAThreadAbortedExceptionOccursWhileInvokingAServiceOperation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 023 - Negative - Should by default close the service channel " +
                    "when a ThreadAbortedException occurs while invoking a service operation", ((string[])(null)));
#line 102
this.ScenarioSetup(scenarioInfo);
#line 103
testRunner.Given("a service consumer is created with an operation aborts the thread", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 104
testRunner.When("the operation is invoked and the thread is aborted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 105
testRunner.Then("the service channel was closed and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 024 - Positive - Should have a customisable trigger strategy " +
            "for when to close the service channel when any exception occurs while invoking a" +
            " service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        public virtual void ConsumingServices_024_Positive_ShouldHaveACustomisableTriggerStrategyForWhenToCloseTheServiceChannelWhenAnyExceptionOccursWhileInvokingAServiceOperation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 024 - Positive - Should have a customisable trigger strategy " +
                    "for when to close the service channel when any exception occurs while invoking a" +
                    " service operation", ((string[])(null)));
#line 107
this.ScenarioSetup(scenarioInfo);
#line 108
testRunner.Given("a service consumer is created with an operation that throws a \'communication\' exc" +
                    "eption", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 109
testRunner.And("the service consumer has a custom service channel close trigger strategy that doe" +
                    "s not ever trigger the closing of the service channnel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
testRunner.When("the operation is called via the Consume method and a \'communication\' exception oc" +
                    "curs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 111
testRunner.Then("the service channel was not closed or aborted, and remains open and usable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 030 - Negative - Should abort the service channel whenever it" +
            " faults")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_030_Negative_ShouldAbortTheServiceChannelWheneverItFaults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 030 - Negative - Should abort the service channel whenever it" +
                    " faults", new string[] {
                        "UnitTest"});
#line 118
this.ScenarioSetup(scenarioInfo);
#line 119
testRunner.Given("a service consumer with a channel that will fault", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 120
testRunner.When("the service channel faults", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
testRunner.Then("the service channel was aborted and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 031 - Negative - Should abort the service channel when there " +
            "is an exception closing the service channel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_031_Negative_ShouldAbortTheServiceChannelWhenThereIsAnExceptionClosingTheServiceChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 031 - Negative - Should abort the service channel when there " +
                    "is an exception closing the service channel", new string[] {
                        "UnitTest"});
#line 124
this.ScenarioSetup(scenarioInfo);
#line 125
testRunner.Given("a service consumer that will throw an \'unexpected\' exception when the service cha" +
                    "nnel is closing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 126
testRunner.When("there is an attempt to close the service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 127
testRunner.Then("the service channel started closing, then aborted and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 032 - Negative - Should abort the service channel when a Thre" +
            "adAbortedException occurs while closing the service channel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        public virtual void ConsumingServices_032_Negative_ShouldAbortTheServiceChannelWhenAThreadAbortedExceptionOccursWhileClosingTheServiceChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 032 - Negative - Should abort the service channel when a Thre" +
                    "adAbortedException occurs while closing the service channel", ((string[])(null)));
#line 129
this.ScenarioSetup(scenarioInfo);
#line 130
testRunner.Given("a service consumer that will abort the thread when the service channel is closing" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 131
testRunner.When("the service channel is closed and the thread is aborted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 132
testRunner.Then("the service channel started closing, then aborted and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 040 - Positive - Should close the service channel when the sc" +
            "ope of a Using block for a service consumer finishes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_040_Positive_ShouldCloseTheServiceChannelWhenTheScopeOfAUsingBlockForAServiceConsumerFinishes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 040 - Positive - Should close the service channel when the sc" +
                    "ope of a Using block for a service consumer finishes", new string[] {
                        "UnitTest"});
#line 138
this.ScenarioSetup(scenarioInfo);
#line 139
testRunner.Given("a service consumer is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 140
testRunner.When("a service consumer is disposed at the end of a using block", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 141
testRunner.Then("the service channel was closed and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 041 - Positive - Should close the service channel when the Ga" +
            "rbage Collector finalises the service consumer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_041_Positive_ShouldCloseTheServiceChannelWhenTheGarbageCollectorFinalisesTheServiceConsumer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 041 - Positive - Should close the service channel when the Ga" +
                    "rbage Collector finalises the service consumer", new string[] {
                        "UnitTest"});
#line 144
this.ScenarioSetup(scenarioInfo);
#line 145
testRunner.Given("a service consumer is created for testing garbage collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 146
testRunner.When("a service consumer is finalised by the garbage collector", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 147
testRunner.Then("the service channel was closed and disposed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation(string typeOfException, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UnitTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 051 - Negative - Should perform the corresponding exception b" +
                    "ehaviour action when there is a <Xyz> Exception - while invoking a service opera" +
                    "tion", @__tags);
#line 153
this.ScenarioSetup(scenarioInfo);
#line 154
testRunner.Given(string.Format("a service consumer is created with an operation that throws a \'{0}\' exception and" +
                        " has a corresponding exception behaviour strategy", typeOfException), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 155
testRunner.When(string.Format("the operation is called and a \'{0}\' exception occurs", typeOfException), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
testRunner.Then("the exception behaviour was invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 051 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is a <Xyz> Exception - while invoking a service opera" +
            "tion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "fault")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "fault")]
        public virtual void ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation_Fault()
        {
            this.ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation("fault", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 051 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is a <Xyz> Exception - while invoking a service opera" +
            "tion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "communication")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "communication")]
        public virtual void ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation_Communication()
        {
            this.ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation("communication", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 051 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is a <Xyz> Exception - while invoking a service opera" +
            "tion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "timeout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "timeout")]
        public virtual void ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation_Timeout()
        {
            this.ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation("timeout", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 051 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is a <Xyz> Exception - while invoking a service opera" +
            "tion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "unexpected")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "unexpected")]
        public virtual void ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation_Unexpected()
        {
            this.ConsumingServices_051_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileInvokingAServiceOperation("unexpected", ((string[])(null)));
        }
        
        public virtual void ConsumingServices_052_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileClosingAServiceChannel(string typeOfException, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UnitTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 052 - Negative - Should perform the corresponding exception b" +
                    "ehaviour action when there is a <Xyz> Exception - while closing a service channe" +
                    "l", @__tags);
#line 165
this.ScenarioSetup(scenarioInfo);
#line 166
testRunner.Given(string.Format("a service consumer that will throw an \'{0}\' exception when the service channel is" +
                        " closing and have a corresponding exception behaviour strategy", typeOfException), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 167
testRunner.When("there is an attempt to close the service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 168
testRunner.Then("the exception behaviour was invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 052 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is a <Xyz> Exception - while closing a service channe" +
            "l")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "communication")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "communication")]
        public virtual void ConsumingServices_052_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileClosingAServiceChannel_Communication()
        {
            this.ConsumingServices_052_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileClosingAServiceChannel("communication", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 052 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is a <Xyz> Exception - while closing a service channe" +
            "l")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "timeout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "timeout")]
        public virtual void ConsumingServices_052_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileClosingAServiceChannel_Timeout()
        {
            this.ConsumingServices_052_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileClosingAServiceChannel("timeout", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 052 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is a <Xyz> Exception - while closing a service channe" +
            "l")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "unexpected")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "unexpected")]
        public virtual void ConsumingServices_052_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileClosingAServiceChannel_Unexpected()
        {
            this.ConsumingServices_052_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAXyzException_WhileClosingAServiceChannel("unexpected", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 053 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is an exception while aborting a service channel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_053_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAnExceptionWhileAbortingAServiceChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 053 - Negative - Should perform the corresponding exception b" +
                    "ehaviour action when there is an exception while aborting a service channel", new string[] {
                        "UnitTest"});
#line 176
this.ScenarioSetup(scenarioInfo);
#line 177
testRunner.Given("a service consumer that will throw an exception while aborting, and has a corresp" +
                    "onding exception behaviour", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 178
testRunner.When("the service channel faults", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 179
testRunner.Then("the exception behaviour was invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 054 - Negative - Should perform the corresponding exception b" +
            "ehaviour action when there is an exception while the Garbage Collector is finali" +
            "sing the service consumer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_054_Negative_ShouldPerformTheCorrespondingExceptionBehaviourActionWhenThereIsAnExceptionWhileTheGarbageCollectorIsFinalisingTheServiceConsumer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 054 - Negative - Should perform the corresponding exception b" +
                    "ehaviour action when there is an exception while the Garbage Collector is finali" +
                    "sing the service consumer", new string[] {
                        "UnitTest"});
#line 182
this.ScenarioSetup(scenarioInfo);
#line 183
testRunner.Given("a service consumer is created for testing garbage collection, and has a destructo" +
                    "r exception behaviour", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 184
testRunner.When("a service consumer is finalised by the garbage collector and an exception occurs " +
                    "in the destructor of the service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 185
testRunner.Then("the exception behaviour was invoked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation(string typeOfException, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UnitTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 060 - Negative - Should bubble an <Xyz> exception back to the" +
                    " caller when there is an exception while invoking a service operation", @__tags);
#line 191
this.ScenarioSetup(scenarioInfo);
#line 192
testRunner.Given(string.Format("a service consumer is created with an operation that throws a \'{0}\' exception", typeOfException), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 193
testRunner.When("the operation is invoked and the exception occurs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 194
testRunner.Then(string.Format("a \'{0}\' exception bubbled up to the calling code", typeOfException), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 060 - Negative - Should bubble an <Xyz> exception back to the" +
            " caller when there is an exception while invoking a service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "fault")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "fault")]
        public virtual void ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation_Fault()
        {
            this.ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation("fault", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 060 - Negative - Should bubble an <Xyz> exception back to the" +
            " caller when there is an exception while invoking a service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "communication")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "communication")]
        public virtual void ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation_Communication()
        {
            this.ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation("communication", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 060 - Negative - Should bubble an <Xyz> exception back to the" +
            " caller when there is an exception while invoking a service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "timeout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "timeout")]
        public virtual void ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation_Timeout()
        {
            this.ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation("timeout", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 060 - Negative - Should bubble an <Xyz> exception back to the" +
            " caller when there is an exception while invoking a service operation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "unexpected")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "unexpected")]
        public virtual void ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation_Unexpected()
        {
            this.ConsumingServices_060_Negative_ShouldBubbleAnXyzExceptionBackToTheCallerWhenThereIsAnExceptionWhileInvokingAServiceOperation("unexpected", ((string[])(null)));
        }
        
        public virtual void ConsumingServices_061_Negative_ShouldNotBubbleAnExceptionBackToTheCallerWhenThereIsAXyzExceptionWhileClosingAServiceChannel(string typeOfException, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UnitTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 061 -  Negative - Should not bubble an exception back to the " +
                    "caller when there is a <Xyz> exception while closing a service channel", @__tags);
#line 203
this.ScenarioSetup(scenarioInfo);
#line 204
testRunner.Given(string.Format("a service consumer that will throw an \'{0}\' exception when the service channel is" +
                        " closing", typeOfException), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 205
testRunner.When("there is an attempt to close the service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 206
testRunner.Then("the exception is not bubbled up to the calling code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 061 -  Negative - Should not bubble an exception back to the " +
            "caller when there is a <Xyz> exception while closing a service channel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "communication")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "communication")]
        public virtual void ConsumingServices_061_Negative_ShouldNotBubbleAnExceptionBackToTheCallerWhenThereIsAXyzExceptionWhileClosingAServiceChannel_Communication()
        {
            this.ConsumingServices_061_Negative_ShouldNotBubbleAnExceptionBackToTheCallerWhenThereIsAXyzExceptionWhileClosingAServiceChannel("communication", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 061 -  Negative - Should not bubble an exception back to the " +
            "caller when there is a <Xyz> exception while closing a service channel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "timeout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "timeout")]
        public virtual void ConsumingServices_061_Negative_ShouldNotBubbleAnExceptionBackToTheCallerWhenThereIsAXyzExceptionWhileClosingAServiceChannel_Timeout()
        {
            this.ConsumingServices_061_Negative_ShouldNotBubbleAnExceptionBackToTheCallerWhenThereIsAXyzExceptionWhileClosingAServiceChannel("timeout", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 061 -  Negative - Should not bubble an exception back to the " +
            "caller when there is a <Xyz> exception while closing a service channel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "unexpected")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Type of Exception", "unexpected")]
        public virtual void ConsumingServices_061_Negative_ShouldNotBubbleAnExceptionBackToTheCallerWhenThereIsAXyzExceptionWhileClosingAServiceChannel_Unexpected()
        {
            this.ConsumingServices_061_Negative_ShouldNotBubbleAnExceptionBackToTheCallerWhenThereIsAXyzExceptionWhileClosingAServiceChannel("unexpected", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 062 - Negative - Should not bubble an exception back to the c" +
            "aller when there is an exception while aborting a service channel")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UnitTest")]
        public virtual void ConsumingServices_062_Negative_ShouldNotBubbleAnExceptionBackToTheCallerWhenThereIsAnExceptionWhileAbortingAServiceChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 062 - Negative - Should not bubble an exception back to the c" +
                    "aller when there is an exception while aborting a service channel", new string[] {
                        "UnitTest"});
#line 214
this.ScenarioSetup(scenarioInfo);
#line 215
testRunner.Given("a service consumer that will throw an exception when the service channel is abort" +
                    "ing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 216
testRunner.When("there is an attempt to close the service channel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
testRunner.Then("the exception is not bubbled up to the calling code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ConsumingServices - 070 - Positive - Should not leak memory")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consuming Services")]
        public virtual void ConsumingServices_070_Positive_ShouldNotLeakMemory()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ConsumingServices - 070 - Positive - Should not leak memory", ((string[])(null)));
#line 222
this.ScenarioSetup(scenarioInfo);
#line 223
testRunner.When("many service consumers are created and used in a tight loop and go out of scope i" +
                    "mmediately over \'15\' seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 224
testRunner.And("garbage collection is performed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
testRunner.Then("there is no significant amount of memory loss", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
